### ISSUE TITLE
Hello world doesn't work

### ISSUE THREAD

**Issue by khuffsmp** [vladbph/zcymatix#1]
Followed the hello world guide but whenever I send Hi it just returns an empty line with the details stating:
`{
"t_utt": "hi"
}`

What did I do wrong? Used the three lines of code and the steps outlined.

**Comment by vladbph** [comment]
@khuffsmp 
Hi! This is very basic example just to demonstrate how easy to build the first project. It returns `{ "t_utt": "hi" }` because the training set does not include utterance "Hi".  Try this:
`.train`
`GREETING: hi`
`GREETING: hello word`
`.prompt`
`GREETING: Hello, my friend! Nice to see you!`

Also take a look at example  [tutorial/macros](https://github.com/vladbph/zcymatix/tree/master/tutorial/macros)
